### PR TITLE
Feature/format long

### PR DESCRIPTION
**Pull request by andymwood**
You should check this before merging. Although it fixes what I think is incorrect behaviour (bug tracker issue 250), it breaks backward-compatibility in the process.

### CODE REVIEW

**Comment by keithbennett** [comment]
Not too keen on this change. Only having one flag for the integer format was a deliberate decision because I didn't think of a good reason for having the fine-grained control and it just makes life more difficult for the end user. Do you disagree?
I've posted 7c801ca which ought to fix any issues in converting the number. What do you think?

**Comment by andymwood** [comment]
Yes, type conversion is a better idea than a more complicated user interface.

However, your patch doesn't fix my problem. It's broken for all negative 4-byte integers. Why is 'data' cast as unsigned, rather than signed integers in lines 595 and 599 of sdffilter.c, when 'default_int' assumes signed integers?

**Comment by keithbennett** [comment]
No reason at all. I'll redo the change with signed ints and merge the changes.

**Comment by keithbennett** [comment]
Okay. Changes applied in fb2790e

**Pull request closed without merging**
